// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfryK38brYAT2pY17CJe7xPmKdP_AwjIM',
    appId: '1:30862017193:web:12812525ff15e599a2dfb8',
    messagingSenderId: '30862017193',
    projectId: 'flutter-apps-73240',
    authDomain: 'flutter-apps-73240.firebaseapp.com',
    databaseURL: 'https://flutter-apps-73240-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-73240.appspot.com',
    measurementId: 'G-P4VS5Z2KMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXpO7LA_yy2nshKSFUEMtpbQ4ZJpbX6Rw',
    appId: '1:30862017193:android:9a63d19285ad069fa2dfb8',
    messagingSenderId: '30862017193',
    projectId: 'flutter-apps-73240',
    databaseURL: 'https://flutter-apps-73240-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-73240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmQgA-GcgCwmNhs05MBlp2olj3AM7eKc',
    appId: '1:30862017193:ios:25f41410a7214df2a2dfb8',
    messagingSenderId: '30862017193',
    projectId: 'flutter-apps-73240',
    databaseURL: 'https://flutter-apps-73240-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-73240.appspot.com',
    iosBundleId: 'com.example.offlineFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmQgA-GcgCwmNhs05MBlp2olj3AM7eKc',
    appId: '1:30862017193:ios:25f41410a7214df2a2dfb8',
    messagingSenderId: '30862017193',
    projectId: 'flutter-apps-73240',
    databaseURL: 'https://flutter-apps-73240-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-73240.appspot.com',
    iosBundleId: 'com.example.offlineFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB8wt-WIZtY1OrJ0qavugJMWUaxqdQO0U',
    appId: '1:30862017193:web:63888eba8303566da2dfb8',
    messagingSenderId: '30862017193',
    projectId: 'flutter-apps-73240',
    authDomain: 'flutter-apps-73240.firebaseapp.com',
    databaseURL: 'https://flutter-apps-73240-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-apps-73240.appspot.com',
    measurementId: 'G-B5R923VTGP',
  );
}
